# permissions for end users to edit keydbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-editor-role
rules:
- apiGroups:
  - keydb.krestomat.io
  resources:
  - keydbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keydb.krestomat.io
  resources:
  - keydbs/status
  verbs:
  - get
