---
- name: keydb k8s resources
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
    - operator_sdk.util
  tasks:
    - name: import keydb role
      import_role:
        name: krestomatio.k8s.v1alpha1.database.keydb
